before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

stages:
  - build
  - deploy

build_stage:
  stage: build
  image: docker
  services:
    - docker:dind
  only:
    - main
  script:
    - docker build --tag=${CI_REGISTRY_IMAGE}:stage .
    - docker push ${CI_REGISTRY_IMAGE}:stage

build_production:
  stage: build
  image: docker
  services:
    - docker:dind
  only:
    - tags
  script:
    - docker build --tag=${CI_REGISTRY_IMAGE}:production .
    - docker push ${CI_REGISTRY_IMAGE}:production

deploy_stage:
  stage: deploy
  only:
    - main
  before_script:
    - apt-get update -qq
    - apt-get install -qq git
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh lipsar@5.8.37.33 "echo ${CI_JOB_TOKEN}; docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com; cd snaptoon-deployment; ls; docker-compose pull api; docker-compose stop -t 1 api; docker-compose up -d api"
